import { useState } from 'react';
import Button from './common/Button';

export default function ExportReportModal({ isOpen, onClose, funnel, platforms }) {
  const [reportType, setReportType] = useState('full');
  const [dateRange, setDateRange] = useState('last_30');
  const [passwordProtect, setPasswordProtect] = useState(false);
  const [password, setPassword] = useState('');
  const [generating, setGenerating] = useState(false);

  if (!isOpen) return null;

  const handleExport = async () => {
    setGenerating(true);

    // Dynamic import to keep bundle small
    const { default: jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF();

    // Header
    doc.setFillColor(107, 77, 61); // #6b4d3d
    doc.rect(0, 0, 210, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text('Glimmora Reach', 14, 18);
    doc.setFontSize(10);
    doc.text('Analytics Report', 14, 26);

    const dateLabel = dateRange === 'last_7' ? 'Last 7 Days' : dateRange === 'last_14' ? 'Last 14 Days' : dateRange === 'last_30' ? 'Last 30 Days' : 'Last 90 Days';
    doc.text(`Period: ${dateLabel}  |  Generated: ${new Date().toLocaleDateString()}`, 80, 26);

    // Reset text color
    doc.setTextColor(0, 0, 0);

    let yPos = 45;

    // Report type label
    const typeLabel = reportType === 'full' ? 'Full Analytics Report' : reportType === 'funnel' ? 'Funnel Analysis Report' : reportType === 'platform' ? 'Platform Comparison Report' : 'Executive Summary';
    doc.setFontSize(14);
    doc.text(typeLabel, 14, yPos);
    yPos += 12;

    // Funnel Data
    if (funnel && (reportType === 'full' || reportType === 'funnel')) {
      doc.setFontSize(12);
      doc.setTextColor(107, 77, 61);
      doc.text('Conversion Funnel', 14, yPos);
      doc.setTextColor(0, 0, 0);
      yPos += 8;

      autoTable(doc, {
        startY: yPos,
        head: [['Metric', 'Value']],
        body: [
          ['Impressions', String(funnel.impressions?.toLocaleString() || '0')],
          ['Clicks', String(funnel.clicks?.toLocaleString() || '0')],
          ['Click Rate', `${funnel.clickRate || 0}%`],
          ['Conversions', String(funnel.conversions?.toLocaleString() || '0')],
          ['Conversion Rate', `${funnel.conversionRate || 0}%`],
          ['Cost per Conversion', `$${funnel.costPerConversion || 0}`],
        ],
        theme: 'striped',
        headStyles: { fillColor: [107, 77, 61] },
        margin: { left: 14 },
      });

      yPos = doc.lastAutoTable.finalY + 15;
    }

    // Platform Data
    if (platforms && platforms.length > 0 && (reportType === 'full' || reportType === 'platform')) {
      doc.setFontSize(12);
      doc.setTextColor(107, 77, 61);
      doc.text('Platform Comparison', 14, yPos);
      doc.setTextColor(0, 0, 0);
      yPos += 8;

      autoTable(doc, {
        startY: yPos,
        head: [['Platform', 'Impressions', 'Clicks', 'CTR', 'CPC', 'Conversions', 'ROAS']],
        body: platforms.map((p) => [
          p.platform,
          p.impressions?.toLocaleString() || '0',
          p.clicks?.toLocaleString() || '0',
          `${p.ctr || 0}%`,
          `$${p.cpc || 0}`,
          String(p.conversions || 0),
          `${p.roas || 0}x`,
        ]),
        theme: 'striped',
        headStyles: { fillColor: [107, 77, 61] },
        margin: { left: 14 },
        styles: { fontSize: 8 },
      });

      yPos = doc.lastAutoTable.finalY + 15;
    }

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Glimmora Reach - Enterprise Ad Campaign Platform', 14, pageHeight - 10);
    doc.text('This is a demo report - data is simulated', 14, pageHeight - 6);

    if (passwordProtect && password) {
      doc.text(`Password Protected: ${password}`, 140, pageHeight - 10);
    }

    // Save
    const fileName = `glimmora-${reportType}-report-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);

    setGenerating(false);
    onClose(true);
  };

  return (
    <div className="fixed inset-0 bg-black/50 z-[100] flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-white rounded-2xl w-full max-w-lg p-6 animate-scale-in" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-lg font-semibold text-gray-900">Export Analytics Report</h3>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 cursor-pointer text-xl">&times;</button>
        </div>

        {/* Report Type */}
        <div className="mb-5">
          <label className="block text-sm font-medium text-gray-700 mb-2">Report Type</label>
          <div className="grid grid-cols-2 gap-2">
            {[
              { id: 'full', label: 'Full Report' },
              { id: 'funnel', label: 'Funnel Analysis' },
              { id: 'platform', label: 'Platform Comparison' },
              { id: 'summary', label: 'Executive Summary' },
            ].map((t) => (
              <button
                key={t.id}
                onClick={() => setReportType(t.id)}
                className={`px-3 py-2 rounded-lg text-sm font-medium transition cursor-pointer ${
                  reportType === t.id ? 'bg-primary text-white' : 'bg-gray-100 text-gray-600 hover:bg-cream'
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {/* Date Range */}
        <div className="mb-5">
          <label className="block text-sm font-medium text-gray-700 mb-2">Date Range</label>
          <select
            value={dateRange}
            onChange={(e) => setDateRange(e.target.value)}
            className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary"
          >
            <option value="last_7">Last 7 Days</option>
            <option value="last_14">Last 14 Days</option>
            <option value="last_30">Last 30 Days</option>
            <option value="last_90">Last 90 Days</option>
          </select>
        </div>

        {/* Password Protection */}
        <div className="mb-6">
          <label className="flex items-center gap-2 cursor-pointer mb-2">
            <input
              type="checkbox"
              checked={passwordProtect}
              onChange={(e) => setPasswordProtect(e.target.checked)}
              className="w-4 h-4 accent-primary"
            />
            <span className="text-sm font-medium text-gray-700">Password protect PDF</span>
          </label>
          {passwordProtect && (
            <input
              type="text"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Enter password for PDF"
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mt-1"
            />
          )}
          {passwordProtect && (
            <p className="text-xs text-gray-400 mt-1">Note: Password will be shown in the PDF footer (demo mode)</p>
          )}
        </div>

        {/* Actions */}
        <div className="flex gap-3">
          <Button variant="outline" className="flex-1" onClick={onClose}>Cancel</Button>
          <Button className="flex-1" onClick={handleExport} disabled={generating}>
            {generating ? (
              <span className="flex items-center gap-2">
                <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg>
                Generating...
              </span>
            ) : 'Export PDF'}
          </Button>
        </div>
      </div>
    </div>
  );
}
